from playwright.sync_api import sync_playwright
exec(open("/home/claude/fb/test_fb.py", encoding="utf-8").read().split("with sync_playwright() as p:")[0])  # 공통 준비 코드 재사용

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 1280, "height": 860}); setup(ctx)
    T = ctx.new_page(); watch(T, "교사")
    T.goto(BASE + "?teacher"); T.wait_for_selector("#login"); T.click("#login"); T.wait_for_selector("#teacher .tabs")
    T.locator("#teacher details.bulk summary").click()
    T.fill("#tv-bulk", "\n".join(f"{i+1} 학생{i+1}" for i in range(20)))
    T.click('#teacher [data-act="bulk-add"]'); T.wait_for_timeout(200)
    T.click('#teacher [data-tab="boards"]')
    for title in ["국어 1", "국어 2", "수학 3", "알림장 4"]:
        T.fill("#tv-new-title", title); T.press("#tv-new-title", "Enter"); T.wait_for_timeout(150)
    check("새 판 4개, 마지막에 만든 판이 선택됨", T.locator("#tv-blist .bitem").count() == 4 and T.locator("#tv-detail .dt-title").input_value() == "알림장 4")
    # 선생님 PC에서 태블릿 화면(가로 3개씩, 쪽 넘김)
    B = ctx.new_page(); B.set_viewport_size({"width": 1180, "height": 820}); watch(B, "태블릿")
    B.goto(BASE); B.wait_for_selector(".wait-code")
    T.click('#teacher [data-tab="settings"]'); T.click('#tv-devices [data-act="approve"]')
    B.wait_for_selector("#app .col-title")
    check("태블릿: 가로 3개 + 쪽 점 2개", B.locator(".col").count() == 3 and B.locator(".page-dots i").count() == 2)
    B.locator(".nav.next").click(); B.wait_for_timeout(150)
    check("태블릿: 다음 쪽에 1개", B.locator(".col").count() == 1)
    B.locator(".nav.next").click(); B.wait_for_timeout(150)
    # 교사: 이름 바꾸기
    T.click('#teacher [data-tab="boards"]')
    T.fill("#tv-detail .dt-title", "알림장 쓰기 4"); T.press("#tv-detail .dt-title", "Enter"); B.wait_for_timeout(300)
    check("이름 바꾸기 → 태블릿에 반영", "알림장 쓰기 4" in [t.inner_text() for t in B.locator(".col-title").all()])
    # 보관 → 태블릿에서 사라짐, 되살리기 → 선택됨
    T.click('#tv-detail [data-act="archive"]'); B.wait_for_timeout(300)
    check("보관 → 태블릿에서 빠짐", "알림장 쓰기 4" not in [t.inner_text() for t in B.locator(".col-title").all()])
    T.locator("#teacher details.archive summary").click()
    T.click('#tv-alist [data-act="restore"]'); T.wait_for_timeout(300)
    check("되살리기 → 그 판이 선택됨", T.locator("#tv-detail .dt-title").input_value() == "알림장 쓰기 4")
    T.click('#tv-detail [data-act="show"]'); B.wait_for_timeout(300)
    check("다시 표시 → 태블릿이 그 판 쪽으로 이동", "알림장 쓰기 4" in [t.inner_text() for t in B.locator(".col-title").all()])
    # 완료 몇 개 후 처음부터 다시
    first = B.locator(".col").first
    first.locator('.card[aria-label^="1번 "]').click(); B.wait_for_timeout(1100)
    first.locator('.card[aria-label^="2번 "]').click(); T.wait_for_timeout(300)
    ftitle = first.locator(".col-title").inner_text()
    T.locator("#tv-blist .bsel", has_text=ftitle).click(); T.wait_for_timeout(100)
    check("완료 2명 반영", "2명 다 했어요" in T.locator("#tv-detail .dt-meta").inner_text(), T.locator("#tv-detail .dt-meta").inner_text())
    T.click('#tv-detail [data-act="reset"]'); T.click('#dlg [data-dlg="ok"]'); B.wait_for_timeout(300)
    check("처음부터 다시 → 태블릿 카드 모두 아직", first.locator(".card.done").count() == 0)
    # 명단: 학생 빼기(그 학생 완료 기록도 지워짐), 번호 다시 매기기, 새로 바꾸기
    first.locator('.card[aria-label^="3번 "]').click(); T.wait_for_timeout(300)
    T.click('#teacher [data-tab="roster"]')
    T.locator('#tv-roster-body tr', has_text="").nth(2).locator('[data-act="del-student"]').click(); T.click('#dlg [data-dlg="ok"]'); B.wait_for_timeout(300)
    check("학생 빼기 → 19명, 태블릿 카드 19장", T.locator("#tv-rcount").inner_text() == "19명" and first.locator(".card").count() == 19)
    done_left = B.evaluate("Object.entries(window.__MOCK.docs).filter(([p]) => p.startsWith('boards/')).some(([p, d]) => Object.keys(d.done || {}).length)")
    check("뺀 학생의 완료 기록도 함께 지워짐", done_left is False)
    T.click('#teacher [data-act="renumber"]'); T.click('#dlg [data-dlg="ok"]'); T.wait_for_timeout(300)
    nos = [T.locator('#tv-roster-body input[data-field="no"]').nth(i).input_value() for i in range(3)]
    check("번호 다시 매기기", nos == ["1", "2", "3"], nos)
    T.fill("#tv-bulk", "가온\n나래\n다솜")
    T.click('#teacher [data-act="bulk-replace"]'); T.click('#dlg [data-dlg="ok"]'); B.wait_for_timeout(300)
    check("명단 새로 바꾸기 → 3명", T.locator("#tv-rcount").inner_text() == "3명" and first.locator(".card").count() == 3)
    # 설정: 잠금번호 바꾸면 태블릿이 새 번호를 씀, 취소 막기
    T.click('#teacher [data-tab="settings"]')
    T.fill("#tv-pin", "4321"); T.click('#teacher [data-act="save-pin"]')
    T.click('#teacher [data-act="self-cancel"][data-v="0"]'); B.wait_for_timeout(300)
    B.locator(".gear").click()
    for k in "1234": B.locator(f'.keys [data-key="{k}"]').click()
    old_rejected = "잠금번호가 달라요" in B.locator(".pin-help").inner_text()
    B.wait_for_timeout(350)
    for k in "4321": B.locator(f'.keys [data-key="{k}"]').click()
    check("바꾼 잠금번호가 태블릿에 바로 적용", old_rejected and B.locator(".sheet-box h3").inner_text() == "태블릿 설정")
    B.locator(".sheet-close").click()
    c = first.locator('.card[aria-label^="1번 "]'); c.click(); B.wait_for_timeout(1100); c.click(); B.wait_for_timeout(200)
    check("취소 막기 → 다시 눌러도 그대로", "done" in c.get_attribute("class") and "선생님께" in B.locator(".tray-msg").inner_text())
    # 판 지우기
    T.click('#teacher [data-tab="boards"]')
    T.click('#tv-detail [data-act="archive"]'); T.wait_for_timeout(200)
    n_arch = T.locator('#tv-alist [data-act="delete"]').count()
    T.locator('#tv-alist [data-act="delete"]').first.click(); T.click('#dlg [data-dlg="ok"]'); T.wait_for_timeout(300)
    check("보관함에서 지우기", T.locator('#tv-alist [data-act="delete"]').count() == n_arch - 1)
    B.screenshot(path="/home/claude/shots/fb-07-tablet-after-ops.png")
    b.close()
print("\n".join(res)); print("통과 %d / 실패 %d" % (sum(r.startswith("OK") for r in res), sum(r.startswith("FAIL") for r in res)))
print("--- errors ---"); print("\n".join(errs) if errs else "(none)")
